### ISSUE TITLE
Include all core team members on team section of the community page

### ISSUE THREAD

**Issue by franckc** [OriginProtocol/website-frontend#17]
Currently the page at https://origin-website-staging.herokuapp.com/community only has a few core team members.
We should include all core team members listed on https://www.originprotocol.com/en/team

For the initial launch it's ok to hardcode those, while we wait for #12 to get implemented.

**Comment by shahthepro** [comment]
#12 is already on master, it shouldn't be a blocker from the CMS repo

**Comment by nickick** [comment]
@franckc we implemented #12 to make it less confusing for Marketing when they get their hands on the CMS, so it's reading from the CMS now. 

Are we planning on doing a db dump to seed the production db? If we are, then I can go ahead and fill in the rest of the core team member profiles so they show up. Otherwise, I'd rather do it once in the production CMS when we stand that up.

**Comment by rolandpo** [comment]
I can fill those in once production is up and running @nickick (if I have write access that is)

**Comment by franckc** [comment]
Sounds great! Thanks @nickick and @rolandpo

**Comment by nickick** [comment]
Thanks for filling these in @rolandpo !
